### PR TITLE
Edit association controller tests

### PR DESCRIPTION
**Pull request by camillevilla**
Edits to RSpec snippets, association tests, and controller test

01_model_migration

02_association_test_orange

03_association_test_tree

04_controller_test

### CODE REVIEW

**Comment by akanshmurthy** [comment]
Looks good to me! Would you mind either adding some screenshots of your changes? I can see the text changes but it would be more helpful to see it in the actual UI. @schaui6 : thoughts?

**Review by akanshmurthy — APPROVED** [review]

**Comment by schaui6** [comment]
@camillevilla @akanshmurthy looks great! my only thought is, if we are going to change 'rails g' to 'rails generate' in step one, then we should keep it consistent and change step four.  Or, we could use it as an opportunity to mention that we could use 'shorthand' aliases

**Comment by schaui6** [comment]
GIF/Screen Recording: 

https://drive.google.com/open?id=0B37lM09NK2l3akc2RGIyY2VQV2M

**Comment by camillevilla** [comment]
Thanks for the GIF @schaui6! I added screenshots above as well.

**Comment by camillevilla** [comment]
For now, I changed the lone instance of `rails g` to `rails generate`. It looks like the Message Board curriculum sticks to `rails generate` as well. It might be better to bump the question of where to discuss aliases up to an issue in [railsbridge/docs](https://github.com/railsbridge/docs).

**Comment by akanshmurthy** [comment]
@camillevilla : cool, stuff looks good! There is 1 minor thing that I noticed. It goes from Step 3 to Step 5 in the screenshot. I think the "On to controller tests" should be Step 4. If you could add a commit directly to the add-testing-curriculum branch, that would be awesome!

**Pull request merged**
